spring:
  application:
    name: spring_opentelemetry
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318
    metrics:
      export:
        otlp:
          endpoint: http://localhost:4318
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318

management:
  tracing:
    sampling:
      probability: 1.0

server:
  shutdown: immediate
logging:
  level:
    com.springotel: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG